"""Evidence loading, figure rendering and the poster evidence builder.

Every figure produced here is drawn only from evidence files generated by the
user and carries a provenance footer (source, evidence status, key/execution/
group counts, configuration, scale factor, creation time, metric definition).
"""
